### ISSUE TITLE
Why node engine versions are limited in package.json?

### ISSUE THREAD

**Issue by fend25** [wobsoriano/trpc-nuxt#104]
Hello! Firstly, I would like to express my gratitude to @wobsoriano for your incredible work.

I have been using the project on Node.js v20, and everything seems to be functioning smoothly. However, I noticed that I need to run `yarn --ignore-engines` when installing dependencies. I am curious about the purpose of the "engines" field in the package.json file. Could you kindly explain why it is included in the project?

**Comment by wobsoriano** [comment]
Removed
