### ISSUE TITLE
`.useQuery` of the same tRPC procedure share the same key even if the transform is different

### ISSUE THREAD

**Issue by mlbiche** [wobsoriano/trpc-nuxt#106]
# The issue

As the `useAsyncData` key defined by `trpc-nuxt` `useQuery` is only based on the procedure path and params, the query returns the same result across pages no matter if there is a transform applied or not.

# Reproduction

Suppose you have two pages `pages/a.vue` and `page/b.vue`:

_pages/a.vue_:
```vue
<template>
  <div>
    {{ todoList }}
    <NuxtLink to="/b">Go to b</NuxtLink>
  </div>
</template>

<script setup lang="ts">
  const { data } = await useTrpcClient().todo.get.useQuery()

  const todoList = computed(() => data.map(({ label }) => label).join(', '))
</script>
```

_pages/b.vue_:
```vue
<template>
  <div>
    {{ data }}
    <NuxtLink to="/a">Go to a</NuxtLink>
  </div>
</template>

<script setup lang="ts">
  const { data } = await useTrpcClient().todo.getText.useQuery(undefined, {
    transform: data => data.map(({ label }) => label).join(', ')
  })
</script>
```

When navigating from `/a` to `/b`, the result is reused as the two queries share the same key.

_NOTE: It may not be helpful for solving this specific issue, but somehow, when navigating from `/a` to `/b`, the error I got was raised in page `a` stating that the computed value `todoList` raised an error because `data` is a string and not an array (so the result of the query in page `b`). It is quite mysterious, but it may be due to the way Nuxt handle data fetching cache and navigation. 🤔 I would have rather expected a bug such as page `b` displaying the raw data from page `a` in the `<div>` Anyway...._

# Possible solution

There may be other solutions, but I would propose to allow a parameter in `useQuery` that would be a key suffix. This way, `pages/b.vue` could be :

```js
  const { data } = await useTrpcClient().todo.getText.useQuery('joined', undefined, {
    transform: data => data.map(({ label }) => label).join(', ')
  })
```

so it does not share the same key with `pages/a.vue`.

Otherwise, exposing the `key` param from `useAsyncData` would be enough to allow to fix this issue.

**Comment by wobsoriano** [comment]
Hey, starting with [v0.10.9](https://github.com/wobsoriano/trpc-nuxt/releases/tag/v0.10.9) you can pass a custom `queryKey` option that overrides the generated key:

```ts
const { $client } = useNuxtApp()

$client.todo.getTodos.useQuery(undefined, {
  queryKey: 'some-key'
})
```

Feel free to open another issue if needed!
