### ISSUE TITLE
docs: improve suggested structure

### ISSUE THREAD

**Issue by qin-guan** [wobsoriano/trpc-nuxt#110]
Hey, thanks for the great work on this project, it's really invaluable! 

The current recommended project structure in the docs can cause cyclic dependency errors in Nuxt. 

The same issue is outlined in trpc-sveltekit [here](https://icflorescu.github.io/trpc-sveltekit/suggested-structure). Would it be better to follow the same suggested structure as the SvelteKit docs?

Would be happy to open a PR and work on this (:

**Comment by wobsoriano** [comment]
Hey, thank you. Feel free to open a PR! Appreciate it.

**Comment by wobsoriano** [comment]
Hey, closing this one as I'm trying to clean up issues. Feel free to reopen!

FYI I based the current structure in the ff. links:

- https://trpc.io/docs/client/nextjs/setup
- https://trpc.io/docs/quickstart

**Comment by qin-guan** [comment]
Hey, no worries! Apologies, I haven't had the time to work on this. Thanks for considering though! 👍
