### ISSUE TITLE
How to add custom AppRouter type?

### ISSUE THREAD

**Issue by Autumnlight02** [wobsoriano/trpc-nuxt#111]
My backend runs outside of my NuxtApp. And I need to import the AppRouter. Issue is now that i cannot register a custom plugin since the example code for that is missing, how can i insert a custom Approuter?

**Comment by wobsoriano** [comment]
Sorry, I am not able to visualize it. Can you make a basic repro? Thanks!

**Comment by wobsoriano** [comment]
If this doesn't help you, please reopen - https://trpc-nuxt.vercel.app/get-started/client

```ts
import { createTRPCNuxtClient, httpBatchLink } from 'trpc-nuxt/client'
import type { AppRouter } from 'from-your-location'

export default defineNuxtPlugin(() => {
  const client = createTRPCNuxtClient<AppRouter>({
    links: [
      httpBatchLink(),
    ],
  })

  return {
    provide: {
      client,
    },
  }
})
```
