### ISSUE TITLE
useQuery data type not nullable

### ISSUE THREAD

**Issue by Blechlawine** [wobsoriano/trpc-nuxt#113]
In Nuxt 3.5.1 the return type of `useAsyncData` was changed and is not nullable by default anymore. we should define it as nullable in our types:
https://github.com/wobsoriano/trpc-nuxt/blob/adeb5a5afdd4ebde7743ca9e16148a0f134cb448/src/client/types.ts#L63

should be:
```typescript
... AsyncData<PickFrom<DataT, PickKeys> | null, DataE>
```

**Comment by wobsoriano** [comment]
Hey, thanks! Would you like to open a PR?
