### ISSUE TITLE
docs: markdown issue

### ISSUE THREAD

**Issue by yk-sgr** [wobsoriano/trpc-nuxt#114]
![image](https://github.com/wobsoriano/trpc-nuxt/assets/24418343/f4151c1e-2bd7-43bc-b155-9596d6c93f7f)

https://trpc-nuxt.vercel.app/get-started/usage/simple

https://github.com/wobsoriano/trpc-nuxt/blob/adeb5a5afdd4ebde7743ca9e16148a0f134cb448/docs/content/1.get-started/2.usage/1.simple.md?plain=1#L37

**Comment by louwers** [comment]
I reported this upstream https://github.com/vuejs/vitepress/issues/2775

**Comment by wobsoriano** [comment]
Looks like an issue on their side. Will update this issue once resolved

<img width="496" alt="Screenshot 2023-08-23 at 09 50 30" src="https://github.com/wobsoriano/trpc-nuxt/assets/13049130/eda57bd7-4112-4d29-ad56-8ea30aff9c80">
