### ISSUE TITLE
Caching trpc routes like/using Nitro cache API

### ISSUE THREAD

**Issue by CharlesBT** [wobsoriano/trpc-nuxt#118]
Hi, I need to cache the output of some trpc routes, is there a way to benefit from the Nitro cache API to do it or have a similar feature.
https://nitro.unjs.io/guide/cache#route-handler

I have seen trpc/next package handle a response caching :
https://trpc.io/docs/server/caching

Thanks

**Comment by wobsoriano** [comment]
Feel free to reopen if my comment above doesn't answer your question.

Trying to clean up issues. Thanks!

**Comment by dimasxp** [comment]
its posible to use nuxt routeRules swr with trpc  ?

**Comment by wobsoriano** [comment]
@dimasxp I am thinking of implementing that. We can swap the `eventHandler` [here](https://github.com/wobsoriano/trpc-nuxt/blob/a54ac5d6cd5a7ec5af7895aba4a47901e04dec12/src/index.ts#L87) with a `cachedEventHandler` and allow passing options. What do you think?

**Comment by wobsoriano** [comment]
@dimasxp I haven't tried it but since all RPC goes through `/api/trpc` by default, maybe you can take advantage of that?

```ts
export default defineNuxtConfig({
  routeRules: {
    '/api/trpc/**': { swr: true },
})
```

**Comment by dimasxp** [comment]
used this solution https://github.com/falcondev-oss/trpc-vue-query/issues/5#issuecomment-2151941113
