### ISSUE TITLE
No `useMutation`

### ISSUE THREAD

**Issue by DarraghOFlaherty** [wobsoriano/trpc-nuxt#119]
Cant seem to access the `useMutation` method in trpc https://trpc.io/docs/client/react/useMutation

**Comment by wobsoriano** [comment]
Yeah, `useQuery` uses the built-in Nuxt `useAsyncData` and there's no way to mutate the data without messing with the global cache. For now, you can use `mutate` and `refresh`:

```ts
const { $client } = useNuxtApp()

const { data, refresh } = await $client.todo.getTodos.useLazyQuery()

const addTodo = async () => {
  await $client.todo.addTodo.mutate({
    userId: 69,
    title: 'Buy a milk',
    completed: false
  })

  refresh()
}
```

**Comment by aaronksaunders** [comment]
yes but this assumes that your mutation function / component has access to the `refresh` method from the original query... guess I need to change the structure of my app

**Comment by wobsoriano** [comment]
Thanks @aaronksaunders!

**Comment by aaronksaunders** [comment]
I solved my problem by just emitting refresh events from my components for
now, will probably figure out a strategy for using a composable, but it all
works now so ready to put together a tutorial video and blog post your
module and drizzle

**Comment by wobsoriano** [comment]
Hi @DarraghOFlaherty, I'm closing this for now.

I really want this module to use built-in Nuxt composables, and until Nuxt releases a mutation composable, you'll need to follow my solution to this question (for now).

If you really want to do mutations, there's a [trpc-vue-query](https://github.com/Colonel-Sandvich/trpc-vue-query) package that might help.

Thanks!

**Comment by wobsoriano** [comment]
You are right, @BitRayDev. There's a composable that will let us mutate the cached value of useAsyncData - [useNuxtData](https://nuxt.com/docs/api/composables/use-nuxt-data#optimistic-updates), and I'm currently in the process of adding a mutation feature using that.
