### ISSUE TITLE
Cannot read properties of undefined (reading 'entity') when defining before mount

### ISSUE THREAD

**Issue by eensander** [wobsoriano/trpc-nuxt#122]
Hello,

So, I'm not sure if this is expected behaviour, but when attempting to access the $trpc client before mount, by placing them directly in Vue's setup section, I get an error implying it is undefined:

```vue
<script lang="ts" setup>
const { $trpc } = useNuxtApp();
const { data, pending, error, refresh } = $trpc.entity.findById.useQuery(1);
</script>
```

Nuxt fails loading and page shows 500 error with:

```
Cannot read properties of undefined (reading 'entity')
```

Reason for top-level defining the query is to be able to access `refresh()` from the template. Using the following workaround, I do get the ability to refresh, though this is obviously not as clean as attempted above:

```vue
<template>
  <button @click="refresh">Refresh</button>
</template>

<script lang="ts" setup>
const { $trpc } = useNuxtApp();

const refresh = ref(async () => {});

onMounted(async () => {
  const query = $trpc.entity.findById.useQuery(1);
  refresh.value = async () => await query.refresh();
});
</script>
```

Am I missing something? What approach are others using to achieve my goal?

Thanks a lot in advance.

**Comment by wobsoriano** [comment]
Interesting. Would you be able to make a basic reproduction via stackblitz?

**Comment by eensander** [comment]
Thanks for your reply. A minimal reproduction on a fresh Nuxt setup can be found at: https://stackblitz.com/edit/nuxt-starter-cwy4t1?file=app.vue

So I understand this behavior is not as expected? That is good to know. Wonder if I am doing something wrong.

**Comment by eensander** [comment]
My mistake has been spotted: The only thing I left unchanged is renaming `plugins/trpc.client.ts` to `plugins/trpc.ts`. With hindsight, I can understand why this let to the error since Nuxt deviates between client and server-logic, and trpc client probably has some serverside plugin logic assigned to it? Nevertheless, I can continue. 

Thanks for the module!
