### ISSUE TITLE
Wrong typing in HttpBatchLinkOptions

### ISSUE THREAD

**Issue by kehwar** [wobsoriano/trpc-nuxt#123]
https://github.com/wobsoriano/trpc-nuxt/blob/4f6cbda2a2ffc7dda9af67a70c7f51eb010ae461/src/client/links.ts#L53

`HttpBatchLinkOptions` should not extend `HTTPLinkOptions`, the headers property have different typing

````ts
// HTTPBatchLinkOptions
((opts: { opList: NonEmptyArray<Operation> }) => HTTPHeaders | Promise<HTTPHeaders>)
````
[HTTPBatchLinkOptions.ts](https://github.com/trpc/trpc/blob/main/packages/client/src/links/HTTPBatchLinkOptions.ts)

````ts
// HTTPLinkOptions
((opts: { op: Operation }) => HTTPHeaders | Promise<HTTPHeaders>)
````
[httpLink.ts](https://github.com/trpc/trpc/blob/main/packages/client/src/links/httpLink.ts)

Also, the `maxURLLength` property is already present in the native `HttpBatchLinkOptions`

**Comment by wobsoriano** [comment]
Hey, would you like to open a PR for this?
