### ISSUE TITLE
client.mutation input is undefined

### ISSUE THREAD

**Issue by duykamke** [wobsoriano/trpc-nuxt#13]
- trpc-nuxt `v0.1.23 - v0.2.0`
- npm `latest`

When calling mutation using `useClient` from client-side/frontend part of a project with input, the input is somehow undefined on the server.

Client:
![image](https://user-images.githubusercontent.com/31849512/173381755-8f9524c6-f40b-4a7b-97fc-c7e4718ac35d.png)
If the object input is set to be required using zod, `console.log` above output:
```
[
  {
    "code": "invalid_type",
    "expected": "object",
    "received": "undefined",
    "path": [],
    "message": "Required"
  }
]
```

Server:
![image](https://user-images.githubusercontent.com/31849512/173382101-ffe57378-2d9a-404f-a760-aa9061367c90.png)

if the object input is set to be optional using zod, `console.log` above output `undefined`

**Comment by duykamke** [comment]
Update. Apparently useClient is not the issue but rather the server-side not recognizing the input.

Payload is still sent normally

![image](https://user-images.githubusercontent.com/31849512/173392171-c28bed50-e028-4e48-ae4d-8ee4b1a26046.png)

**Comment by wobsoriano** [comment]
What happens if you delete `node_modules` and `.nuxt` and try again?

**Comment by duykamke** [comment]
> What happens if you delete `node_modules` and `.nuxt` and try again?

Tried still doesn't work.

**Comment by duykamke** [comment]
@wobsoriano Found the problem. When using with `superjson` transformer somehow all input is parsed to undefined. Removed `superjson` and it worked.

Sorry for the inconvenience!

**Comment by wobsoriano** [comment]
Yeah I should add support to transformers. Thanks!
