### ISSUE TITLE
Does trpc calls on server-side works same as `$fetch` calls?

### ISSUE THREAD

**Issue by cawa-93** [wobsoriano/trpc-nuxt#14]
Nuxt docs says:
> During server-side rendering, calling $fetch to fetch your internal [API routes ](https://v3.nuxtjs.org/guide/directory-structure/server)will directly call the relevant function (emulating the request), saving an additional API call.

Does this work for [trpc-nuxt](https://github.com/wobsoriano/trpc-nuxt)? Does it make sense to replace the default fetch implementation with a `$fetch` helper?

**Comment by cawa-93** [comment]
I sometimes encounter strange errors like:
```
TRPCClientError: request to https://kitlink.io/trpc/shortLink.click?batch=1 failed, reason: write EPROTO 140124978730944: error: 14094410: SSL routines: ssl3_read_bytes: sslv3 alert handshake failure: ../ deps / openssl openssl / ssl / record / rec_layer_s3.c: 1546: SSL alert number 40
```

This error occurs during server rendering. The request to api fails, but works correctly on the client during hydratation.

I have an assumption that such problems would not arise, in this case when server directly call the relevant function and don't try make https request

**Comment by essarn** [comment]
It seems that the request is always made on the client side and not emulated during SSR.

**Comment by cawa-93** [comment]
This probably also may be resolved by https://github.com/wobsoriano/trpc-nuxt/issues/4#issuecomment-1192491398

**Comment by essarn** [comment]
We really need zoom Nej men annars kan man ju ändå göra kpgotnpt det
