### ISSUE TITLE
TRPCError.message not forwarded to client

### ISSUE THREAD

**Issue by CharlesBT** [wobsoriano/trpc-nuxt#143]
Hi the trpc-client doesn't cach properly the TRPCError and did not forward TRPCError.message.

I had to edit ./dist/client/index.mjs of your package to replace line 94 
if (e instanceof FetchError && e.response) {
by 
if (e.constructor.name === "FetchError" && e.response) {

If there is no nasty border effect could you integrate this fix in the next release
Thanks :)

**Comment by wobsoriano** [comment]
That is weird. It works on my machine 😆. I'm wondering what might be causing the issue, though.

**Comment by wobsoriano** [comment]
Released a new version but before you upgrade, can you try if installing `ofetch` fixes your issue?
