### ISSUE TITLE
TRPCError.cause not forwarded to client side

### ISSUE THREAD

**Issue by CharlesBT** [wobsoriano/trpc-nuxt#144]
Hi following tRPC spec https://trpc.io/docs/server/error-handling

I throw a TRPCError with cause property on server side but the cause property is not forwarded to the trpc client error

**Comment by wobsoriano** [comment]
I assume this is related to https://github.com/wobsoriano/trpc-nuxt/issues/143 so I'm closing this. Feel free to reopen!
