### ISSUE TITLE
tRPC v11 branch

### ISSUE THREAD

**Issue by Flowko** [wobsoriano/trpc-nuxt#148]
Would you please publish the new v11 changes so we can start use the newer version, Thanks!

https://github.com/wobsoriano/trpc-nuxt/issues/135

**Comment by wobsoriano** [comment]
There are new type updates so I have to fix those first

**Comment by wobsoriano** [comment]
In fact, they removed the `@trpc/core` package where the current trpc-11 branch is based off

**Comment by wobsoriano** [comment]
Released a beta version https://www.npmjs.com/package/trpc-nuxt/v/0.11.0-beta.0

```bash
npm install trpc-nuxt@0.11.0-beta.0
```
