### ISSUE TITLE
How to disable Nuxt cache between pages with tRPC?

### ISSUE THREAD

**Issue by dihmeetree** [wobsoriano/trpc-nuxt#153]
I have 2 pages (say `index.vue` and `about.vue`.. both look like this
```ts
<script setup lang="ts">
const { $client } = useNuxtApp()

const hello = await $client.hello.useQuery({ text: 'client' })
</script>

<template>
  <div>{{ hello.data }}</div>
</template>
```

When I navigate between the 2 pages.. data is loaded fresh the first time, and then cached with further navigations. How do I prevent the page data from getting cached?

**Comment by wobsoriano** [comment]
Have you tried providing a custom key?

```ts
// index.vue
const hello = await $client.hello.useQuery({ text: 'client' })
```

```ts
// about.vue
const hello = await $client.hello.useQuery({ text: 'client' },  {
  queryKey: 'some-other-key'
})
```

**Comment by wobsoriano** [comment]
Your stackblitz link fails when installing deps

**Comment by Jimmyzm** [comment]
You may need to refresh the cache manually using [refreshNuxtData](https://nuxt.com/docs/api/utils/refresh-nuxt-data) or [clearNuxtData](https://nuxt.com/docs/api/utils/clear-nuxt-data) somewhere like brefore routing, 'cause the `nuxt-link` use client-side route by default and the data was fetched on server-side.

Or you can just use client-side call:
```
const { data } = await $client.hello.useQuery({ text: 'client' }, { server: false })
```

**Comment by Jimmyzm** [comment]
> Hi Jimmy, thanks for that info. The only issue is that my query is actually being run from a `Component.server.vue` file (server component), not a client component. I believe `refreshNuxtData` and `clearNuxtData` would need to be run from a client component?

You can use `refreshNuxtData` and `clearNuxtData` at the page component which include the server component. Now the page component should not be a server component yet, not like nextjs's app folder. Something like:
```
onBeforeRouteLeave(() => {
  clearNuxtData()
})
```

**Comment by wobsoriano** [comment]
Appreciate you answering this @Jimmyzm
