### ISSUE TITLE
Cannot stringify arbitrary non-POJOs TRPCClientError

### ISSUE THREAD

**Issue by jemrickrioux** [wobsoriano/trpc-nuxt#16]
I always get this error: `Cannot stringify arbitrary non-POJOs TRPCClientError`

Here are my files:
`~/server/api/trpc/index.ts`

```ts
import type { inferAsyncReturnType } from '@trpc/server'
import * as trpc from '@trpc/server'
import * as  z  from 'zod'
import type { OnErrorPayload } from 'trpc-nuxt/api'

import * as PrismaPkg from '@prisma/client'
const {PrismaClient} = PrismaPkg
const client = new PrismaClient()


export const router = trpc.router()
    // queries and mutations...
    .query('hello',{
    // validate input with Zod
        async resolve(req) {
        console.log(req)
        // use your ORM of choice
        return {
            message: `Hello`
        }
    },
})

```

`~/pages/index.vue`

```vue
<script setup lang="ts">
import MyButton from '@/components/MyButton.vue'
import {useAsyncQuery, useFetch} from "#imports";
const router = useRouter()

const {data} = await useAsyncQuery(["hello"]);
</script>

<template>
  <NuxtLayout name="home">
    <section class="flex flex-col h-max justify-center">
      <div class="bg-primary-600 rounded-lg p-10 text-white text-2xl" >{{data}}</div>
      [...]
    </section>
  <NuxtLayout name="home">
</template>
```

Looking at the error message, seems to be that my trpc endpoint is refusing connections.

```
TRPCClientError: request to http://localhost:3000/trpc/hello?batch=1&input=%7B%7D failed, reason: connect ECONNREFUSED ::1:3000
    at Function.from (file:///Users/jean-emrickrioux/Dev/stakeFrites/_tools/trakmos-project/trakmos-nuxt/.nuxt/dist/server/server.mjs:33400:14)
    at file:///Users/jean-emrickrioux/Dev/stakeFrites/_tools/trakmos-project/trakmos-nuxt/.nuxt/dist/server/server.mjs:34021:42
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  originalError: FetchError: request to http://localhost:3000/trpc/hello?batch=1&input=%7B%7D failed, reason: connect ECONNREFUSED ::1:3000
      at ClientRequest.<anonymous> (file:///Users/jean-emrickrioux/Dev/stakeFrites/_tools/trakmos-project/trakmos-nuxt/node_modules/node-fetch/src/index.js:108:11)
      at ClientRequest.emit (node:events:527:28)
      at Socket.socketErrorListener (node:_http_client:454:9)
      at Socket.emit (node:events:527:28)
      at emitErrorNT (node:internal/streams/destroy:164:8)
      at emitErrorCloseNT (node:internal/streams/destroy:129:3)
      at processTicksAndRejections (node:internal/process/task_queues:83:21) 
```

**Second try:**

Changed the trpc directory to `~/server/api/trpc`
```
   [nuxt] [request error] Invalid lazy handler result. It should be a function:
  at ./node_modules/h3/dist/index.mjs:299:17  
  at processTicksAndRejections (node:internal/process/task_queues:96:5)  
  at async ./node_modules/h3/dist/index.mjs:420:19  
  at async Server.nodeHandler (./node_modules/h3/dist/index.mjs:370:7)

```

My changed `nuxt.config.ts` looks like this:
```ts
export default defineNuxtConfig({
trpc: {
    baseURL: 'http://localhost:3000/api', // defaults to http://localhost:3000
    endpoint: '/trpc', // defaults to /trpc
  },
}
```

**Comment by jemrickrioux** [comment]
Looking at the error message, seems to be that my trpc endpoint is refusing connections.

if that can help.

**Comment by wobsoriano** [comment]
I'll take a look at this asap. Thanks for reporting!

**Comment by jemrickrioux** [comment]
No worries, I wouldn't mind being of help, I think that it has to do with the server not properly serving the trpc endpoint, is there anything that comes to mind?

I could investigate in the direction you point me to.

Thanks

**Comment by wobsoriano** [comment]
Which node version are you using?

**Comment by wobsoriano** [comment]
Okay, I'm using Node v16 and it works well on that version. I tried v18 and I'm getting your error now

**Comment by wobsoriano** [comment]
https://github.com/wobsoriano/trpc-nuxt/issues/15

**Comment by jemrickrioux** [comment]
I removed my node_modules, .nuxt and yarn.lock files/directories.

I switched to node 16.15.1

I then ran yarn install.

I still get the same error.

----

I tried the same using your trpc-nuxt repo and I still get that infamous error: `Cannot stringify arbitrary non-POJOs TRPCClientError`

---

I tried playing around in the module files and if I  `console.log($client.query)` it outputs a promise in my browser console, that gets fulfilled with the right data. The error seems to be happening on the server call which messes up the useAsyncData composable.

Sorry for being a pain in the ***.

If it can make it easier for you here are some steps to reproduce:
1. `git clone https://github.com/stakefrites/trakmos-nuxt `
2. `cd trakmos-nuxt`
3. `git checkout trpc`
4. `yarn install`
5. `yarn dev`

You will find the trpc folder in `~/server/trpc/index.ts`
You will find my client call in `~/pages/index.vue`

Appreciate the help a lot, I'd love to give you a hand on some other things to repay my dues 😄

**Comment by wobsoriano** [comment]
Can you try Node v16.14.2?

**Comment by jemrickrioux** [comment]
It gives me the same error, unfortunately.

**Comment by jemrickrioux** [comment]
Nuxt CLI v3.0.0-rc.4                                                                                                                                                                                                                                                                                          12:19:47
RootDir: /Users/jean-emrickrioux/Dev/stakeFrites/_tools/trakmos-project/trakmos-nuxt                                                                                                                                                                                                                          12:19:48
Nuxt project info:                                                                                                                                                                                                                                                                                            12:19:48

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.15.1`
- Nuxt Version:     `3.0.0-rc.2`
- Package Manager:  `yarn@1.22.18`
- Builder:          `vite`
- User Config:      `css`, `typescript`, `meta`, `modules`, `build`, `windicss`, `vite`
- Runtime Modules:  `nuxt-windicss@2.4.2`, `@vueuse/nuxt@8.8.0`, `@pinia/nuxt@0.1.9`, `@nuxtjs/eslint-module@3.1.0`, `trpc-nuxt@0.2.2`
- Build Modules:    `-`
------------------------------

**Comment by wobsoriano** [comment]
If you upgrade to `3.0.0-rc.4`, what happens?

**Comment by jemrickrioux** [comment]
To summarize:

Node must be at version 16 and we must use nuxt : `^3.0.0-rc.4`
