### ISSUE TITLE
Support for `watch: false` in `useQuery`

### ISSUE THREAD

**Issue by warflash** [wobsoriano/trpc-nuxt#166]
To align things further with the `useFetch` experience and give more fine grained control over fetches, adding `watch: false` as an option would be great.

Taken from the [useFetch](https://nuxt.com/docs/api/composables/use-fetch#params) docs:
"You can completely ignore reactive sources by using `watch: false`. Together with `immediate: false`, this allows for a fully-manual useFetch"

**Comment by Jimmyzm** [comment]
I think you might be able to add it directly since `useQuery` is a wrapper for `useAsyncData`:
```
const { data } = $client.user.list.useQuery(undefined, { watch: false })
```

**Comment by warflash** [comment]
@Jimmyzm There is a bit of custom logic around how `watch` is handled (which makes sense) and so there's a minor adjustment needed. See #167
