### ISSUE TITLE
Features/Milestones for trpc-nuxt v1.0.0

### ISSUE THREAD

**Issue by Q16solver** [wobsoriano/trpc-nuxt#17]
Hey! I just have some questions about if there is a plan to integrate this as an official adapter package for nuxt e.g. `@trpc/nuxt` since I don't see any other similar open source projects that do the same thing. It's definitely very difficult to maintain these amazing projects, so I just wanted to set my expectations right since I'm only really just using it and trying things out and not working on it myself. I completely understand if there's no plans for anything at all.

Anyways, TLDR: wanted to try and build a chat app for fun and found some lacking things/wishlist of some of the things/issues I was wondering if it would be implemented (again, I don't know how difficult these things would be, so it's just a daydream of mines if you can forgive me for saying):

- Integration for using with dbs/Prisma? Trying this right now, though it doesn't seem to work, maybe I'm just dumb or I think this might require something from the plugin? (Edit: Prisma works, I was just being dumb with the integration)
- Subscriptions/Websockets support? Definitely something on my wishlist if I'm planning on doing real-time things
- Which leads to needing things like integrating packages like superjson for Dates etc from Prisma

I can add more if I find any, but these were some of the things I found were a bit more important since I want to continue using trpc-nuxt, thanks for listening to my blabber tho!

**Comment by wobsoriano** [comment]
Leaving this here for now https://github.com/trpc/trpc/issues/2084

**Comment by wobsoriano** [comment]
Hi! I am waiting for [this PR](https://github.com/trpc/trpc/pull/2085) to get merged for my next update.
