### ISSUE TITLE
Failed to parse URL on server side

### ISSUE THREAD

**Issue by ambrizals** [wobsoriano/trpc-nuxt#170]
**Runtime Environment** : Bun 1.1.7
**OS**: Mac OS 14.4.1 (Sonoma)

First i have found some issue on HTTP Link, technically all of API called is run correctly on client or browser. But if we call trpc on server environment, i got some error like this.

```
WARN  [Vue Router warn]: No match found for location with path "/project"

Failed to parse URL from /api/trpc/blog.article?input=%7B%22page%22%3A1%2C%22perPage%22%3A2%7D

  at TRPCClientError.from (node_modules/@trpc/client/dist/TRPCClientError-38f9a32a.mjs:38:16)
  at node_modules/@trpc/client/dist/httpUtils-b9d0cb48.mjs:128:36
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

I was assuming this will happen because server only getting api path not for full url path, currently i can using this for quick fixes but this gonna not ideal for everyone.

```typescript
import { httpLink } from "@trpc/client";
import { createTRPCNuxtClient, httpBatchLink } from "trpc-nuxt/client";
import type { AppRouter } from "~/server/trpc/routers";

export default defineNuxtPlugin((nuxtApp) => {
  let url = "api/trpc";

  if (import.meta.server) {
    url = `http://localhost:${nuxtApp.$config.port}/${url}`;
  }

  /**
   * createTRPCNuxtClient adds a `useQuery` composable
   * built on top of `useAsyncData`.
   */
  const batchClient = createTRPCNuxtClient<AppRouter>({
    links: [
      httpBatchLink({
        url: url,
      }),
    ],
  });

  const client = createTRPCNuxtClient<AppRouter>({
    links: [
      httpLink({
        url: url,
      }),
    ],
  });

  return {
    provide: {
      batchClient,
      client,
    },
  };
});

```

**Comment by wobsoriano** [comment]
I've never experienced this issue. Can you create a basic repro? The default for both `httpLink` and `httpBatchLink` is `/api/trpc`

**Comment by jaichinger** [comment]
Hey @ambrizals, I'm not sure if you've worked this out already, but I think it's happening because you accidentally imported `httpLink` from `@trpc/client` instead of `trpc-nuxt/client`.

**Comment by ambrizals** [comment]
> Hey @ambrizals, I'm not sure if you've worked this out already, but I think it's happening because you accidentally imported `httpLink` from `@trpc/client` instead of `trpc-nuxt/client`.

Whoopss, sorry i didn't see it at all and yeah is already fix thank you.
