### ISSUE TITLE
Recommended Setup: Property Greeting Does Not Exist On Type

### ISSUE THREAD

**Issue by IzakJackson** [wobsoriano/trpc-nuxt#171]
Hi,

I'm following the recommended setup: https://trpc-nuxt.vercel.app/get-started/usage/recommended

And encountering this error: `Property 'greeting' does not exist on type 'Ref<{ greeting: string; } | null>'.ts-plugin(2339)`

This is my app.vue:

```
<script setup lang="ts">
const { $client } = useNuxtApp();

const hello = await $client.hello.useQuery({ text: 'client' });
</script>

<template>
  <div>
    <p>{{ hello.data?.greeting }}</p>
    <Button>Button</Button>
  </div>
</template>
```

Doing just: `{{ hello.data?.greeting }}` returns `{ "data": { "greeting": "hello client" }, "pending": false, "error": null, "status": "success" }`

Where: `{{ hello.data?.greeting }}` returns nothing.

This is my `~/server/trpc/routers/index.ts`:

```
import { z } from 'zod';
import { publicProcedure, router } from '../trpc';

export const appRouter = router({
  hello: publicProcedure
    .input(
      z.object({
        text: z.string().nullish(),
      })
    )
    .query(({ input }) => {
      return {
        greeting: `hello ${input?.text ?? 'world'}`,
      };
    }),
});

// export type definition of API
export type AppRouter = typeof appRouter;
```

Following the simple setup works, but I'd prefer to use the recommended setup.

**Comment by IzakJackson** [comment]
Doing this in `app.vue` solves the issue, but is this best practice?:

```
<p v-if="hello.data.value" class="text-white">
      {{ hello.data?.value.greeting }}
    </p>
    ```

**Comment by wobsoriano** [comment]
This is something from Nuxt. I'll try to find an existing report on their side and I'll add it here.

For now what you want to do is destructure it before using inside the template:

```vue
<script setup lang="ts">
const { $client } = useNuxtApp();

const { data } = await $client.hello.useQuery({ text: 'client' });
</script>

<template>
  <div>
    <p>{{ data?.greeting }}</p>
    <Button>Button</Button>
  </div>
</template>
```
