### ISSUE TITLE
Fix `useLazyQuery`

### ISSUE THREAD

**Issue by ClementNerma** [wobsoriano/trpc-nuxt#173]
Hi there!

I'm currently writing an application using this project (which is great btw!) but I'm encountering a few problems.

One of them is that `useLazyQuery` seems to have some pieces missing. Notably, how do I re-trigger the same query, but with different parameters? The returned `execute` callback doesn't allow to do that...

**Comment by wobsoriano** [comment]
Hi! Have you tried passing in a ref/reactive as a param? Like:

```ts
const { $client } = useNuxtApp()
const text = ref('robert')

const { data } = await $client.hello.useLazyQuery(text)

setTimeout(() => {
  text.value = 'clement' // updating the ref should rerun the query 
}, 500)
```
