### ISSUE TITLE
Missing examples

### ISSUE THREAD

**Issue by damisparks** [wobsoriano/trpc-nuxt#178]
The examples are missing: [https://trpc-nuxt.vercel.app/examples/basic](https://trpc-nuxt.vercel.app/examples/basic)

See image below
<img width="1197" alt="image" src="https://github.com/user-attachments/assets/11f894e6-7fe8-4ec1-99b6-a10197e55ac6">

**Comment by wobsoriano** [comment]
Closing this. I will be updating the docs site to use Vitepress instead since docus [is not maintained anymore](https://github.com/nuxt-themes/docus/issues/1016).
