### ISSUE TITLE
'$client' is of type 'unknown'.ts-plugin(18046) const $client: unknown

### ISSUE THREAD

**Issue by fl5brkv** [wobsoriano/trpc-nuxt#179]
**This is the code**

<template>
  <div>
    {{data}}
  </div>
</template>

<script setup lang="ts">
const { $client } = useNuxtApp()

// const {data} = await $client.user.getUsers().query()

const data = ref('')

onMounted(async () => {
  try {
    const response = await $client.user.getUsers().query();
    data.value = response;
  } catch (error) {
    console.error('Failed to fetch users:', error);
  }
});
</script>

**And this is the error on $client**

'$client' is of type 'unknown'.ts-plugin(18046)
const $client: unknown

**Comment by wobsoriano** [comment]
Most of the time removing `.nuxt` folder and `node_modules` + reinstall fixes this issue

**Comment by wobsoriano** [comment]
https://github.com/wobsoriano/trpc-nuxt/issues/91
