### ISSUE TITLE
Not working on Cloudflare Workers

### ISSUE THREAD

**Issue by essarn** [wobsoriano/trpc-nuxt#18]
It's not possible to run this when deployed on Cloudflare Workers. I'm getting the error `global is not defined`. Might have something to do with how the fetch workers there. Maybe this two repos could be of help to solve the problem. 

https://github.com/esamattis/trpc-cloudflare-worker
https://github.com/valu-digital/npm-packages/tree/master/packages/trpc-fetch-api-adapter

**Comment by wobsoriano** [comment]
Need to polyfill the global object

**Comment by essarn** [comment]
Actually I'm dumb.. the worker tried calling the localhost trpc server in production. Everything works now, thanks for the awesome Nuxt TRPC implantation!

**Comment by essarn** [comment]
@wobsoriano Do have time for another question regarding running on Cloudflare Workers?

It seems that using `useAsyncQuery` doesn't run on the server during SSR. Instead it runs on the client side and there is not data in the initial HTML sent from the server.

**Comment by essarn** [comment]
@wobsoriano hi, do you have any update on my second issue?

**Comment by wobsoriano** [comment]
Hi! I am waiting for [this PR](https://github.com/trpc/trpc/pull/2085) to get merged for my next update.

**Comment by wobsoriano** [comment]
Hey, just released v3. Probably fixes your issue @essarn

**Comment by essarn** [comment]
Yes it should work, looking forward to using the library with v10 support.
