### ISSUE TITLE
How pass request headers?

### ISSUE THREAD

**Issue by cawa-93** [wobsoriano/trpc-nuxt#2]
How I can pass `useRequestHeaders(['cookie'])` using `useAsyncQuery` ? I store JWT in cookie and want send it for context creation.

**Comment by cawa-93** [comment]
The documentation describes how to _receive_ authorization data on server-side and create a context with it. But it does not disclose how to _send_ authorization data.

**Comment by duykamke** [comment]
@wobsoriano Hey! What about passing request headers to the server itself, like using Authorization header `Bearer ${token}`?
useAsyncData doesn't support sending headers, only the implicit callback $fetch that is used, hence useAsyncQuery also does not support sending headers as well.

**Comment by wobsoriano** [comment]
Ahh that’s right, opening

**Comment by duykamke** [comment]
Thank you so much!
