### ISSUE TITLE
useAsyncQuery is not correctly typed

### ISSUE THREAD

**Issue by hugohabicht01** [wobsoriano/trpc-nuxt#22]
First of all, thanks for creating this project, its a massive joy to work with. 
But I've noticed a couple of bugs around useAsyncQuery:
1. The options that one can pass to nuxt/useAsyncData aren't correctly typed, according to volar, theyre typed as `never`, although they should be `string[]`. Example: https://github.com/hugohabicht01/howdoyoudo/blob/master/pages/user/%5Bid%5D.vue#L14
2. The data property that useAsyncQuery emits, seems to always be `Pick<RETURNTYPE, never>` (RETURNTYPE being the type that the trpc query returns). Example: https://github.com/hugohabicht01/howdoyoudo/blob/master/pages/user/%5Bid%5D.vue#L44

**Comment by wobsoriano** [comment]
The next release (v0.3.0) removes the composables currently available and you will have to create your own client plugin. I'll write an example of how to do it too. 

Current implementation limits the users (data transformations, etc.).

**Comment by birdlavv** [comment]
Looks like it has to do with this line:
https://github.com/wobsoriano/trpc-nuxt/blob/master/src/runtime/client.ts#L51

Changing from
`): Promise<AsyncData<PickFrom<ReturnType<Transform>, PickKeys>, TError>> {` to
`): Promise<AsyncData<ReturnType<Transform>, TError>> {`

Resolves the typing error but it looks like you lose the picking helper.

**Comment by wobsoriano** [comment]
Nuxt can't type array picks too. You might be interested with the `transforms` property https://v3.nuxtjs.org/api/composables/use-async-data#params

**Comment by mlbiche** [comment]
> Nuxt can't type array picks too. You can use the `transform` option for now to get proper types:
> 
> <img alt="Screen Shot 2022-10-06 at 5 16 50 PM" width="514" src="https://user-images.githubusercontent.com/13049130/194440800-2010e7af-911f-4986-805e-f25be81b6255.png">

@wobsoriano Do you have a ticket on Nuxt repo that references this issue so I can follow it? Cheers!

**Comment by mlbiche** [comment]
@wobsoriano It seems Nuxt correctly types array picks since version `3.5.*` 🎉
