### ISSUE TITLE
Nuxt 2

### ISSUE THREAD

**Issue by blocka** [wobsoriano/trpc-nuxt#23]
Does this work with nuxt 2? Some of the code samples seems to imply nuxt 3, but there was no explicit mention in the docs.

**Comment by wobsoriano** [comment]
Only tested on Nuxt 3 and I don't have plans to support Nuxt 2. Thanks!

**Comment by blocka** [comment]
Might be worth just dropping a note in the readme! You already have one with regards to node compatibilty.

**Comment by pencilcheck** [comment]
That sucks

**Comment by wobsoriano** [comment]
@pencilcheck v4 might support nuxt 2. Let’s see
