### ISSUE TITLE
useClientHeaders returns an empty object

### ISSUE THREAD

**Issue by mahdiboomeri** [wobsoriano/trpc-nuxt#24]
### Describe the issue
Currently headers in `useClient` composable only work in SSR context. headers defined in `useClientHeaders` are stored in `localStorage` which is only available in the client.
one solution would be to remove the `nuxtApp.ssrContext` condition around headers in `trpc.createTRPCClient`. this way headers are properly defined in the client requests but they will still be empty during initial SSR rendering because localStorage (or seasonStorage) is unavailable. to fix that we could use `useState` composable instead of vueuse's `useStorage`, this way the value can be defined in the server and passed to the client during the hydration step.

I made a PR for fixing this issue: #25

**Comment by wobsoriano** [comment]
https://github.com/wobsoriano/trpc-nuxt/pull/25
