### ISSUE TITLE
useInfiniteQuery() not working

### ISSUE THREAD

**Issue by juls0730** [wobsoriano/trpc-nuxt#27]
`useInfintieQuery()` is a simple way to implement infinite scrolling with your applications. However, the server throws syntax errors (no crash tho) and there appears to be no way to use and infinite query in the client. in order to get this feature working you would need to add a `.infinitequery` function to the `useClient()` function. I will try and get a working pull request up soon (in school rn so cant lol)

https://trpc.io/docs/v9/useInfiniteQuery

**Comment by wobsoriano** [comment]
Closing this as of v4. You can create your own set of composables now.

**Comment by elonsalfati** [comment]
@wobsoriano - would be really awesome to get it implemented.

**Comment by Shhu** [comment]
Would be great to have this implemented by the package
