### ISSUE TITLE
V10 support

### ISSUE THREAD

**Issue by juls0730** [wobsoriano/trpc-nuxt#29]
With a trpc v10 stable release on the horizon I think we should be able to use v10 in our Nuxtjs projects. Possibly adding a `next` or `v10` branch and adding another package to npmjs would be advisable.

Regards, juls0730 <juls07@juls07.dev>

**Comment by essarn** [comment]
Maybe we should create a base package for use with just Vue and then create a connector that works with Nuxt?

**Comment by wobsoriano** [comment]
Just released trpc-nuxt v3 with Node 18 support. 

Support for TRPC v10 will be trpc-nuxt v4 :)

**Comment by wobsoriano** [comment]
Just released trpc-nuxt v3 with Node 18 support. 

Support for trpc v10 for trpc-nuxt v4. What do you think?

**Comment by juls0730** [comment]
Amazing, thanks for your assistance 

Regards juls0730 <juls07@juls07.dev>

**Comment by Q16solver** [comment]
I do agree in perhaps having a `next` branch for us to test things now that trpc is in rc mode

**Comment by juls0730** [comment]
@Q16solver yeah, I do think @wobsoriano should add a `next` branch but a version difference does work if it's not perfect

**Comment by Q16solver** [comment]
Yes, now that there is an rc version for v10, the api should be fairly stable now, is it possible to get a v0.4 of trpc nuxt or some version of the package to support v10? I think we can reopen this issue right now @juls0730 @wobsoriano

**Comment by wobsoriano** [comment]
Yeah, I got the v10 RC Notification. Let's reopen.

**Comment by wobsoriano** [comment]
OTW https://github.com/wobsoriano/trpc-nuxt/pull/36

**Comment by juls0730** [comment]
So with this pull request are you suggesting we replace v9 support with v10 support on the main branch?

**Comment by wobsoriano** [comment]
@juls0730 yes but need to finalize it and would be happy to have it reviewed by you all!
