### ISSUE TITLE
Reactive inputs?

### ISSUE THREAD

**Issue by birdlavv** [wobsoriano/trpc-nuxt#31]
First off, thank you @ wobsoriano for the awesome module!

Is there support for passing reactive inputs?
Calling `refresh()` does not bust the cache regardless of the internal state of the `userId` `ref`
```typescript
const { data, pending, error, refresh } = await useAsyncQuery(
  ['getUser', { name: userId.value }],
  {
    lazy: false,
  }
);
```
[With the native useFetch we use a `() =>` on the url to keep the URL params reactive on calling `refresh()`](https://v3.nuxtjs.org/getting-started/data-fetching#refreshing-data)

Is there something similar we can do with `useAsyncQuery` to keep the input parameters reactive?

This reactivity would help greatly with pagination flavored use-cases.

Reproduction link:
https://stackblitz.com/edit/github-mj8gus?file=server%2Ftrpc%2Findex.ts,app.vue

Any assistance would be greatly appreciated.

**Comment by wobsoriano** [comment]
Hi! Please use v0.4.x of trpc-nuxt and feel free to create your own composables 😄
