### ISSUE TITLE
Have trpc as peer dependency

### ISSUE THREAD

**Issue by Q16solver** [wobsoriano/trpc-nuxt#35]
Is it possible to perhaps copy from how `trpc-next` does this https://github.com/trpc/trpc/blob/next/packages/next/package.json
I believe this will help reduce maintenance burden on always needing to keep track with versions, with only needing to upgrade when library needs it as a dev dependency and leave responsibility to userland to maintain trpc package version

**Comment by wobsoriano** [comment]
peer dep in v3 and v4 now.

**Comment by Q16solver** [comment]
Thanks! This is amazing, I can setup renovate to auto update trpc on my side now
