### ISSUE TITLE
Have default query/mutate api match trpc behaviour

### ISSUE THREAD

**Issue by Q16solver** [wobsoriano/trpc-nuxt#39]
Hey! Congrats on the v0.4 release! I'm not sure if you had time to read out some of the issues I commented on the PR, so I'll raise it here for more visibility

> Hello! First of all, amazing work! I've been trying it out and testing it and rewriting all my api endpoints. I have a question about how the useAsyncData under the hood works. Since it's always async, that means that after querying/mutating, the data object that gets returned could be null and doesn't immediately get the result after awaiting? If I have an onClick that calls this, will it be able to actually get the data back instead of null (also doesn't this mean I have to always do null if checks).
> 
> I think this is a little different from how the previous client.query in trpc-nuxt v0.3 worked, and if I called await on that, it would always return the exact type of the result, did that also useAsyncData under the hood? If not, perhaps we can have default behaviour being the same thing so it's simpler, and useAsyncData being a separate api to call if we need data, pending, error.. etc

![image](https://user-images.githubusercontent.com/50786287/201502798-c4afbee3-fe59-434a-92af-a8a2aaa7d27d.png)
![image](https://user-images.githubusercontent.com/50786287/201502815-193b4264-ee79-406e-9a13-69985b7f644f.png)

**Comment by wobsoriano** [comment]
I agree with this, now we don't need to have a separate client for it.

**Comment by wobsoriano** [comment]
Thanks for the suggestion!

**Comment by Q16solver** [comment]
@wobsoriano Awesome, this makes using the syntax so much more nicer, thanks so much!
