### ISSUE TITLE
Superjson transformer giving errors

### ISSUE THREAD

**Issue by Q16solver** [wobsoriano/trpc-nuxt#41]
I believe this may have something to do with removing the trpc wrapper? It was working before when I was using beta package

![image](https://user-images.githubusercontent.com/50786287/201506622-574e59a7-9df6-4006-b7d4-033836b9bfb8.png)

![image](https://user-images.githubusercontent.com/50786287/201506664-07036a01-7954-42bb-9ac5-468215d3c612.png)

**Comment by Q16solver** [comment]
Closing this since it's probably my fault with something else

**Comment by wobsoriano** [comment]
Interesting. I'm using superjson in the playground and didn't encounter any issue.

**Comment by Q16solver** [comment]
Yeah, it only seems to be happening after I build and run npm start, I’ll have a further look into this
