### ISSUE TITLE
Official recipe for websocket integration

### ISSUE THREAD

**Issue by Q16solver** [wobsoriano/trpc-nuxt#45]
Hello, I'm trying to figure out a very nice way of integrating websockets with trpc nuxt, and just looking through the docs of trpc, though it seems like it isn't as straightforward as I thought, and I'm not sure how to use it alongside with things like httpBatchLink and wsLink, the environment variables I need (seems like I need to split up with the WS base url, then the WS port so then I can pass it in http server) etc. Quite a little confused as to the proper way to set this up for production purposes and using it from client side so it would be quite helpful if we could get some help on that, much appreciated c:

![image](https://user-images.githubusercontent.com/50786287/202887257-927da54b-e0e7-4085-8216-fd46e9a1e225.png)

**Comment by Extarys** [comment]
I'd love to know if you found an elegant solution to this? :)

**Comment by Q16solver** [comment]
@Extarys I've found an elegant enough way, although I haven't properly tested it out yet, so just a warning if you plan on using it for production https://github.com/Esposter/Esposter/blob/main/server/middleware/websocketServer.ts

**Comment by wobsoriano** [comment]
https://github.com/wobsoriano/trpc-nuxt/discussions/95

**Comment by Q16solver** [comment]
Amazing stuff! Just a few things I found while reading through the example and documentation, I think the ws should be added as a plugin to nitro, so it has to be placed in `~/server/plugins/ws.ts` as specified by https://nuxt.com/docs/guide/directory-structure/server#server-plugins
It would also be great if this was put into a section in the docs for how to setup if it hasn't already, thanks so much!
