### ISSUE TITLE
Cookies are missing on Server

### ISSUE THREAD

**Issue by noxz-dev** [wobsoriano/trpc-nuxt#46]
Hi,

If I try to access the cookies on the h3Event they are empty

```js
export const createContext = (event: H3Event) => {
  const cookies = parseCookies(event); // cookies = {}

  ...
}
 ```

I think it's a ssr problem like written here: https://trpc.io/docs/ssr#q-why-do-i-need-to-forward-the-clients-headers-to-the-server-manually-why-doesnt-trpc-automatically-do-that-for-me

Is it possible to access the context and set the headers?

It was working with 0.3.* (trpc 9) am I missing something else?

**Comment by wobsoriano** [comment]
Hey, thanks for noticing that! Updated docs

https://trpc-nuxt.vercel.app/get-started/tips/headers

**Comment by noxz-dev** [comment]
Thanks, works perfectly
