### ISSUE TITLE
useAsyncQuery and useClient are of type any

### ISSUE THREAD

**Issue by duykamke** [wobsoriano/trpc-nuxt#5]
For some reason after a certain version update, both useAsyncQuery and useClient are no longer typesafe.
Tried to do a clean installation of dependencies by deleting `package-lock.json` and `node_modules`, and running `npm ci`.

![image](https://user-images.githubusercontent.com/31849512/170651728-fc6c48c8-87b8-4360-9ae9-d593e7906120.png)
![image](https://user-images.githubusercontent.com/31849512/170651734-7ea45b17-31d3-4121-9e92-e96498fc6d89.png)

**Comment by wobsoriano** [comment]
Should be fixed now. Vueuse probs. Thanks for reporting!
