### ISSUE TITLE
Nuxt v3

### ISSUE THREAD

**Issue by MichaelVonB** [wobsoriano/trpc-nuxt#50]
Hi, 

thanks for your work, really enjoying nuxt and trpc. 
As nuxt just got a stable 3.0 release, I tried to upgrade my project to nuxt 3..0.0
This was my package json
```
  },
  "devDependencies": {
    "nuxt": "3.0.0-rc.8",
  },
  "dependencies": {
    "@trpc/client": "^9.27.2",
    "@trpc/server": "^9.27.2",
    "primevue": "^3.12.6",
    "trpc-nuxt": "^0.2.7",
    "zod": "^3.18.0"
  }
```
and my nuxt.config
```
import { defineNuxtConfig } from 'nuxt';

export default defineNuxtConfig({
  modules: ['trpc-nuxt'],
  trpc: {
    baseURL: '', // Set empty string (default) to make requests by relative address
    endpoint: '/trpc', // defaults to /trpc
  },
  typescript: {
    strict: true, // required to make input/output types work
  },
});

```

following your guide. After upgrading to nuxt 3.0 I got an error ` Nuxt module should be a function: [object Object] `.
When I got rid of the `modules: ['trpc-nuxt']` everything compiled again but all useClient usaged broke, as expected. 
Then I found https://github.com/wobsoriano/trpc-nuxt and your docs https://trpc-nuxt.vercel.app/get-started
which does not use the module nor the autoImport useClient(). 
Now I am a bit confused which version of nuxt-trpc will be maintained and what should be the way to go forward.

**Comment by cawa-93** [comment]
You are probably looking for [v0,3](https://github.com/wobsoriano/trpc-nuxt/tree/v3)
v0.4 is an totally breacking change. It Requires a completely different installation and does not contain composite functions. You can't just upgrade to a new version. Depending on the project, you may need to redo a lot

**Comment by MichaelVonB** [comment]
Yeah, I just realized that i was just on the v0.3 Branch. 
Just finished the rewrite according to v0.4 🥱
