### ISSUE TITLE
Docs problems: For "simple" usage a type is imported from the wrong place, and `.value` needs to be accessed explicitly

### ISSUE THREAD

**Issue by BracketJohn** [wobsoriano/trpc-nuxt#55]
1. In the docs it says to import:
https://github.com/wobsoriano/trpc-nuxt/blob/bb2d1ef8ddc2226b2de52b45212b10fdac4bb46f/docs/content/1.get-started/2.usage/1.simple.md?plain=1#L81

for the "simple" usage. Instead, that should probably be:
```ts
import type { AppRouter } from "~/server/api/trpc/[trpc]"
```

as `~/server/trpc/routers` does not exist in the "simple" setup.

2. In the docs the example page for the simple case looks like this:

https://github.com/wobsoriano/trpc-nuxt/blob/bb2d1ef8ddc2226b2de52b45212b10fdac4bb46f/docs/content/1.get-started/2.usage/1.simple.md?plain=1#L115

This doesn't work - for some reason (and maybe this is actually a bug?), you have to explicitly ask for `.value`:
```html
    <p>Data: {{ hello.data.value?.greeting }}</p>
```

**Comment by wobsoriano** [comment]
Thanks! https://github.com/wobsoriano/trpc-nuxt/commit/410dcf8a11f24fd52c63387f8f32bc74b0889b8c

**Comment by thisduck** [comment]
@wobsoriano With a new setup, I got the same issue as mentioned in point #2 in the original post.

Have to use `value`. Is this a bug?

```
    <p>Data: {{ hello.data.value?.greeting }}</p>
```
