### ISSUE TITLE
issue upgrading to trpc-nuxt 0.4.4

### ISSUE THREAD

**Issue by ZainW** [wobsoriano/trpc-nuxt#56]
error
```sh
ERROR	[nuxt] [request error] [unhandled] [500] Package import specifier "#imports" is not defined in package /var/task/node_modules/trpc-nuxt/package.json imported from /var/task/node_modules/trpc-nuxt/dist/client/index.mjs
```

just upgraded to trpc-nuxt 0.4.4 and facing this issue in production

i did add the following to my nuxt.config.ts but still no luck in production

not sure why it works locally but not in prod
```
build: {
    transpile: ['trpc-nuxt/client'],
  },
```

**Comment by wobsoriano** [comment]
Thanks for reporting! I’ll check this one in a bit.

**Comment by codaxiom** [comment]
Hi I have the same issue in 0.5.0
