### ISSUE TITLE
[Question]: Is it possible to have global error handling for redirecting unauthorised requests?

### ISSUE THREAD

**Issue by Q16solver** [wobsoriano/trpc-nuxt#59]
Hello!

I wanted to do something similar to the pic below, but wasn't sure if that was currently possible since navigateTo doesn't exist inside the onError function. This should be something that's done like the axios interceptor where I check the code to see if it's 401 (unauthorised) or 403 (forbidden) then redirect user to login page. Was wondering if it's currently supported since I couldn't find any docs for nuxt api handler nor the links part and I think those are the only places where this seems reasonable. Other places like middleware don't seem to be the correct places to do this.

![image](https://user-images.githubusercontent.com/50786287/209470254-ad849fab-de99-4264-b437-ec6371a99cf4.png)

**Comment by huzaifahj** [comment]
This would be great. Currently doing this by `try` `catch`ing every client query and handling the errors in one function

**Comment by mubaidr** [comment]
I believe this can be achieved by adding a TRPC middle-ware to check session for every request and you can return `unauthorized` error. Or I am missing something?

```ts
export const privateProcedure = publicProcedure.use(async ({
  ctx,
  next,
}) => {
  if (!ctx.user) {
    throw new TRPCError({
      code: 'UNAUTHORIZED',
    })
  }

  return next({
    ctx,
  })
},
)
```

For more information: https://github.com/wobsoriano/trpc-nuxt/issues/69#issuecomment-1428194619

**Comment by Q16solver** [comment]
@mubaidr The issue isn't to do with returning the error from the backend, it's more of a frontend issue of trying to redirect routes once trpc realises it's an unauthorised request. Curremtly there's no way to do that, although I'm not sure if it's because of upstream trpc package

**Comment by mubaidr** [comment]
Oh ok, but regarding the request intercepting TRPC has `links`: https://trpc.io/docs/links

**Comment by Q16solver** [comment]
That does seem like a possible solution though it doesn’t seem like it will be simple and don’t see any standards for doing it, at least for nuxt side

**Comment by Q16solver** [comment]
Error links works like a charm, closing this

**Comment by mubaidr** [comment]
@Q16solver Can you please sample code?

**Comment by Q16solver** [comment]
@mubaidr https://github.com/Esposter/Esposter/blob/main/services/trpc/errorLink.ts

**Comment by birdlavv** [comment]
Fixed link https://github.com/Esposter/Esposter/blob/main/packages/app/services/trpc/errorLink.ts

**Comment by birdlavv** [comment]
Link broke again, created gist, https://gist.github.com/birdlavv/14ca4c76a7b42f1b6d4a856b60277fbc
