### ISSUE TITLE
v0.1.22 input typing and useStorage error

### ISSUE THREAD

**Issue by duykamke** [wobsoriano/trpc-nuxt#6]
After updating to v0.1.22 (Thank you for the quick fix). Typings for useAsyncQuery and useClient are now back, but input params are somehow undefined as shown in picture 1.

Picture 2 depicts useStorage error when running in dev though I'm not even using useRequestHeaders. This is now a breaking change and I have to revert trpc-nuxt back to the last version.

Both errors persist after clean install of dependencies.

![image](https://user-images.githubusercontent.com/31849512/170721927-ba027bdb-0df6-4882-b9de-e4b724aa35fb.png)
![image](https://user-images.githubusercontent.com/31849512/170722077-ce1311d6-260c-441f-9579-f1b7a4c94a54.png)

**Comment by wobsoriano** [comment]
Fixed the not defined error in v0.1.23. Thanks for reporting.

For the TS error, I'll check if it's related to dot notation paths. Be sure to set `typescript.strict` to `true` in your nuxt config

**Comment by duykamke** [comment]
@wobsoriano Thank you for the quick turnaround! Could you also please check the `refresh` callback in useAsyncQuery? It works with `server: false` but not without.

**Comment by wobsoriano** [comment]
So I tried with the dot notation merged routers and without `server: false` and the types and refresh function works

<img width="592" alt="Screen Shot 2022-05-27 at 9 21 40 AM" src="https://user-images.githubusercontent.com/13049130/170739573-785a3771-7997-4cb3-b9bc-13b1f1129c31.png">

**Comment by duykamke** [comment]
@wobsoriano actually nvm I did a clean npm install and somehow everything resolved!

**Comment by wobsoriano** [comment]
Thanks! Feel free to re-open if you found any issues again.

**Comment by duykamke** [comment]
@wobsoriano v0.1.23 has not been released yet AFAIK
