### ISSUE TITLE
TRPCClientError: Unable to transform response from server

### ISSUE THREAD

**Issue by therealokoro** [wobsoriano/trpc-nuxt#64]
Hello sir.

So I tried using this in a fresh project, following the steps provided in the docs. But I keep getting this error

```
TRPCClientError: Unable to transform response from server
    at transformResult (transformResult-6fb67924.mjs?v=c31f6aa1:74:15)
    at httpBatchLink.mjs?v=c31f6aa1:188:41
```

I feel this is a trpc error and not a trpc-nuxt error, but I felt it is best checked here first before possibly moving to trpc repo to file an issue.

## Reproduction
https://github.com/therealokoro/trpc-nuxt-app

**Comment by wobsoriano** [comment]
The [API handler](https://trpc-nuxt.vercel.app/get-started/usage/simple) should be inside `api/trpc/[trpc].ts` file.

Also, `useQuery` is built-on top of `useAsyncData` so it's best to use `query` if you're trying to call it inside a function:

```ts
async function query() {
  const data = await $client.auth.getUser.query({ id: 2 })
}
```

In your code, you could also do

```vue
<script setup lang="ts">
const { $client } = useNuxtApp()
const { data: user, error } = await $client.auth.getUser.useQuery({ id: 2 })
</script>

<template>
  <div class="dark">
    <div class="p-10 bg-primary/40">
      <h1>Hello</h1>
      <pre>{{ user }}</pre>
    </div>
  </div>
</template>
```

**Comment by therealokoro** [comment]
My bad. Thank you sir
