### ISSUE TITLE
[Error]: The requested module '@trpc/server' does not provide an export named 'resolveHTTPResponse' 

### ISSUE THREAD

**Issue by nvhoang55** [wobsoriano/trpc-nuxt#67]
After installing trpc-nuxt **v.0.3.7** on Nuxt app v.3, I met this error:

`[worker reload] [worker init] The requested module '@trpc/server' does not provide an export named 'resolveHTTPResponse' `
```js

import { resolveHTTPResponse } from "@trpc/server";
  ^^^^^^^^^^^^^^^^^^^
  SyntaxError: The requested module '@trpc/server' does not provide an export named 'resolveHTTPResponse'
  at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
  at async ModuleJob.run (node:internal/modules/esm/module_job:189:5)
  at async Promise.all (index 0)
  at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
  at async loadESM (node:internal/process/esm_loader:91:5)
  at async handleMainPromise (node:internal/modules/run_main:65:12)
```

My package.json:
```json
 "dependencies": {
    "@trpc/client": "^10.9.0",
    "@trpc/server": "^10.9.0",
    "trpc-nuxt": "~0.3.7",
    "zod": "^3.20.2"
  }
```

Does anyone have a solution for it? I appreciate it a lot.

**Comment by wobsoriano** [comment]
This is expected as `@trpc/server` v10 doesn't have an export named `resolveHTTPResponse`. You have to install v9 of both `@trpc/client` and `@trpc/server`.

**Comment by nvhoang55** [comment]
> This is expected as `@trpc/server` v10 doesn't have an export named `resolveHTTPResponse`. You have to install v9 of both `@trpc/client` and `@trpc/server`.

Thank you a lot. It worked!

**Comment by robsel118** [comment]
is there an update on this?
I install v9 but not the code in the playground doesn't work anymore
