### ISSUE TITLE
[Question] How to set cookie in trpc router?

### ISSUE THREAD

**Issue by mubaidr** [wobsoriano/trpc-nuxt#69]
Can some one please confirm what is the procedure to set cookie in the trpc router?

`setCookie` expects event as first argument and I donot know to access it in TRPC query context. 

Is there draw back if I send the content to front end and then set cookie at component level?

```json
"trpc-nuxt": "^0.6.0",
"nuxt": "^3.1.2",
"@trpc/client": "^10.10.0",
"@trpc/server": "^10.10.0",
```

**Comment by Extarys** [comment]
I was able to pass `req` and `res` to the context, but I had a warning. It seems that accessing those from an `H3Event` is deprecated.
```
declare class H3Event implements Pick<FetchEvent, "respondWith"> {
    "__is_event__": boolean;
    node: NodeEventContext;
    context: H3EventContext;
    constructor(req: IncomingMessage, res: ServerResponse);
    get path(): string | undefined;
    /** @deprecated Please use `event.node.req` instead. **/
    get req(): IncomingMessage;
    /** @deprecated Please use `event.node.res` instead. **/
    get res(): ServerResponse<IncomingMessage>;
    respondWith(r: H3Response | PromiseLike<H3Response>): void;
}
```
So we need a way to add `event.node.req/res` to the context. I tried, but the `createContext` method expect `H3Event` as type of object.

I believe this would need to be implemented in this library, or I might be forgetting something. This would allow us to use the H3 `setCookie` method and read/set `headers`

**Comment by mubaidr** [comment]
For now I have this code, please let me know if this can be improved: 

Setup a nuxt middleware to parse cookie/header
```ts
export default defineEventHandler(async (event) => {
  event.context.user = getSessionFromRequest(event)
})

Pass this context to TRPC context
```ts
export function createContext(event: H3Event) {
  return {
    db,
    event,
    user: event.context.user as JwtPayload,
  }
}
```

**Comment by Extarys** [comment]
@mubaidr Thanks for the reply. Are you using Nuxt 3? On my side `getSessionFromRequest` is not defined.

Also, this method would be difficult to implement when you need to set multiple cookies originally. :/ I'd use `useCookie` from Nuxt, but sensible data need `httpOnly` and you can't set this on the client side.

**Comment by mubaidr** [comment]
Yes, Nuxt 3. This method `getSessionFromRequest(event)` is custom function to extract and parse cookie.

Example: 
```ts
export function getSessionFromRequest(event: H3Event) {
  const cookie = getCookie(event, COOKIE_NAME)

  if (!cookie)
    return null

  // const unsignedSession = cookieSignature.unsign(cookie, COOKIE_SECRET)

  // if (!unsignedSession)
  //   return null

  return verifyJWT(cookie)
}
```

**Comment by Extarys** [comment]
Oh, I mean, I'm trying to `set`/send cookies from the server to the client. :laughing: (trpc to frontend)

But getting them was also an issue, so that's for that snippet :)

**Comment by mubaidr** [comment]
```ts
export function setSessionToRequest(event: H3Event, jwtPayload: JwtPayload) {
  const token = encodeJWT(jwtPayload)
  // const signedSession = cookieSignature.sign(token, COOKIE_SECRET)

  setCookie(event, COOKIE_NAME, token, {
    httpOnly: true,
    sameSite: true,
    maxAge: SESSION_EXPIRES / 1000,
    expires: new Date(Date.now() + SESSION_EXPIRES),
    secure: !IS_DEV,
  })
}
```

**Comment by Extarys** [comment]
That doesnt work inside a router query or mutation. I had to pass the whole `node` in the context

https://github.com/trpc/trpc/discussions/3769#discussioncomment-4982989

I appreciate you took the time <3

**Comment by mubaidr** [comment]
Offcourse you need access to h3 event/context. As explained here: https://github.com/wobsoriano/trpc-nuxt/issues/69#issuecomment-1428194619

It works fine, I am using this technique. It behaves perfectly fine.

P.s. If you are trying to set/get cookie on client side it will not work because it is an http cookie.
