### ISSUE TITLE
How to use useQuery with a transform function

### ISSUE THREAD

**Issue by kouts** [wobsoriano/trpc-nuxt#78]
Thanks for this great library.
I have a question regarding the usage of `useQuery` with a transform function.
I'm using it like this:
```
<script setup lang="ts">
const { $client } = useNuxtApp()

const { data, pending } = await $client.admin.getContent.useQuery(undefined, {
  lazy: true,
  transform(value) {
    return value
  }
})
</script>
```
but I get a Typescript error on the transform function
![image](https://user-images.githubusercontent.com/2233663/227140437-26c65b2d-3b36-4d9d-8069-cdada3503694.png)

what am I missing?

**Comment by mlbiche** [comment]
It's been a while and I hope you have solved your issue, but I think it should be

```
transform: (value) => {
  return value
}
```

**Comment by kouts** [comment]
Thanks @mlbiche
