### ISSUE TITLE
Docs page not working

### ISSUE THREAD

**Issue by MiguelCollado** [wobsoriano/trpc-nuxt#81]
Hi! I have notice that the Docs page for this repo is not working. Its spitting me a 500 Internal Server Error from vercel. I attach a screenshot of the problem

https://trpc-nuxt.vercel.app/

![image](https://user-images.githubusercontent.com/22587459/228482370-d313fcf4-3d74-4645-85a6-bc09c8e5bee0.png)

Hope this gets resolved soon! Thank you for your time!

**Comment by AbuBakrBenMhenni** [comment]
https://trpc-nuxt-docs.vercel.app/

**Comment by wobsoriano** [comment]
Fixed https://github.com/wobsoriano/trpc-nuxt/commit/be55641338eccc953149083f67cabcc86b24b0a1
