### ISSUE TITLE
useQuery not reactive(watch) with ref inputs

### ISSUE THREAD

**Issue by nconnector** [wobsoriano/trpc-nuxt#85]
This documented way of using useQuery refreshes on `count` change but always sends the initial `count.value`
```
const { data } = await $client.hello.useQuery(
  { num: count.value },
  { watch: [count] }
);
```

The obvious workaround to get reactivity is useAsyncData and query with an input getter:
```
const { data } = await useAsyncData(
  () => $client.hello.query({ num: count.value }),
  { watch: [count] }
)
```

Am I missing something or is there no way to support dynamic inputs in useQuery?

**Comment by wobsoriano** [comment]
You can now do this in ^0.10.4

```ts
const id = ref(1)

const { data } = await $client.todo.getTodo.useQuery(id, {
  watch: [id],
})

setTimeout(() => {
  id.value++
}, 1000)
```

Input will accept a ref or non-ref value. If it's a ref, you'll still have to add it to the `watch` property to make it reactive for now.

**Comment by wobsoriano** [comment]
Update: You can omit the watch property if input is a ref.

```ts
const id = ref(1)

const { data } = await $client.todo.getTodo.useQuery(id)

setTimeout(() => {
  id.value++
}, 1000)
```

For reactive state, convert a specific property to a computed first:

```ts
const state = reactive({ id: 1 })

const id = computed(() => state.id)

const { data: todo, pending, error, refresh } = await $client.todo.getTodo.useQuery(id)

setTimeout(() => {
  state.id++
}, 1000)
```

**Comment by apinrdw** [comment]
@wobsoriano can the input accept more than 1 ref as an object? like nuxt composable `useFetch` the `query` or `params` options can accept multiple refs

**Comment by janvennemann** [comment]
@apinrdw I ran into this issue as well today, as my procedure accepts an object as input, not just a simple number. I was able to solve this by using a computed ref that i use to create a new object that holds multiple refs:

```ts
const limit = ref(15)
const currentPage = ref(1)
const queryInput = computed(() => ({
  page: currentPage.value,
  limit: limit.value,
}))

const { data } = await $client.document.all.useQuery(queryInput, { watch: [queryInput] })
```

@wobsoriano is this the recommended way to do this? The docs and your example only work for single ref inputs of primitive JS values. If the input is an object that holds multiple refs it will not work without the computed ref.

**Comment by wobsoriano** [comment]
@janvennemann SLR but that is exactly how you would do it. Libraries like [vue-query](https://github.com/TanStack/query/discussions/5912#discussioncomment-6842776) suggest doing it as well. Check [this](https://github.com/DamianOsipiuk/vue-query/issues/5) out too.

If you check Vue's [convention and best practices](https://vuejs.org/guide/reusability/composables.html#input-arguments) around composables' input arguments, it's written there that

> If you are writing a composable that may be used by other developers, it's a good idea to handle the case of input arguments being refs or getters instead of raw values.

So I think passing in an object with refs inside it is kind of breaking the convention?

**Comment by wobsoriano** [comment]
@warflash I'll review and add more improvements as we proceed. Even improved https://github.com/wobsoriano/trpc-nuxt/pull/151, making getters auto watchable as well.
