### ISSUE TITLE
TRPC release v10.20.0 breaking change on `HTTPLinkOptions`

### ISSUE THREAD

**Issue by Colonel-Sandvich** [wobsoriano/trpc-nuxt#87]
In this release the interal types were changed for `HTTPLinkOptions`
In [this PR](https://github.com/trpc/trpc/pull/4175) the type `HTTPLinkOptions` that this package uses got renamed to `HTTPLinkBaseOptions` but also in the process the `headers` property got moved to a new type `HTTPLinkOptions` declared [here](https://github.com/trpc/trpc/pull/4175/files#diff-671e79295e2c31c75769e93c3c10ebaea24b2dc466d3a82d0865548a8a1e318dR12).

This breaks typing of options in `httpLink` and `httpBatchLink` provided by this package.

The fix is simple, just need to change the import from `'@trpc/client/dist/links/internals/httpUtils'` to `'@trpc/client/dist/links/httpLink'`.

PR [here](https://github.com/wobsoriano/trpc-nuxt/pull/88)

**Comment by fskarmeta** [comment]
Not sure if this is related but i got type error that the url property is not part of httpBatchLink
![image](https://user-images.githubusercontent.com/69222982/232857563-3651c36d-0cd8-467d-9b1a-8a95a8053cb5.png)

maybe im doing something wrong, but i have the impression that this is how the api is used.

@wobsoriano thanks for this module :D

**Comment by Colonel-Sandvich** [comment]
What versions of `@trpc/server`, `@trpc/client` and `trpc-nuxt` do you have installed?

**Comment by fskarmeta** [comment]
@trpc/server 10.20.0
@trpc/client 10.20.0
trpc-nuxt 0.8.0
