### ISSUE TITLE
Feature Request: `useLazyQuery`

### ISSUE THREAD

**Issue by Colonel-Sandvich** [wobsoriano/trpc-nuxt#89]
Add a simple wrapper function around the existing `useQuery` to set the lazy option to true.

```ts
$client.post.getPosts.useLazyQuery(<input>)
```
Equivalent to
```ts
$client.post.getPosts.useQuery(<input>, { lazy: true })
```

@wobsoriano If this is something that you think is worth adding I can open a PR based on [this diff](https://github.com/wobsoriano/trpc-nuxt/compare/next...Colonel-Sandvich:trpc-nuxt:next) (Playground changes optional)

**Comment by wobsoriano** [comment]
Yeah feel free to open a PR!

**Comment by wobsoriano** [comment]
Released in https://github.com/wobsoriano/trpc-nuxt/releases/tag/v0.10.10

Thanks!
